# Generated by Django 3.2.8 on 2021-10-23 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('id_payment', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('original_value', models.FloatField(max_length=30, verbose_name='Valor original')),
                ('new_value', models.FloatField(max_length=30, verbose_name='Novo Valor')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('not_disponible', 'Not_Disponible'), ('requested', 'Requested'), ('released', 'Released'), ('denied', 'Denied')], default='disponible', max_length=14)),
                ('doc_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero do Boleto')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('id_register', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('site', models.CharField(max_length=100, verbose_name='Site')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('user_agent', models.CharField(max_length=512)),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('id_payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='core.payment')),
            ],
            options={
                'verbose_name': 'log de pagamento',
                'verbose_name_plural': 'logs de pagamentos',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='id_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='Fornecedor'),
        ),
    ]
